Repository swift-nav/piksi_buildroot, pull requests merged in 2018-07, with the labels that each got.

#717 Revert change to read buffer size [DEVC-938]
  package/endpoint_adapter/src/endpoint_adapter.c
Labels: needs backport

#714 [v16] Removed fpga_error_moni, added pfw_welcome
  Config.in
  board/piksiv3/rootfs-overlay/etc/init.d/S84_1_failsafe_update
  board/piksiv3/rootfs-overlay/etc/init.d/S84_1_fpga_error_moni
  board/piksiv3/rootfs-overlay/etc/init.d/S84_2_reset2defaults
  board/piksiv3/rootfs-overlay/etc/init.d/S84_3_upgrade_tool
  board/piksiv3/rootfs-overlay/etc/init.d/S87pfw_welcome
  package/fpga_error_moni/Config.in
  package/fpga_error_moni/fpga_error_moni.mk
  package/pfw_welcome/Config.in
  package/pfw_welcome/pfw_welcome.mk
  package/pfw_welcome/src/Makefile
  package/pfw_welcome/src/pfw_welcome.c
Labels: needs backport/forwardport

#718 Removed fpga_error_moni, added pfw_welcome (#714)
  Config.in
  board/piksiv3/rootfs-overlay/etc/init.d/S84_1_failsafe_update
  board/piksiv3/rootfs-overlay/etc/init.d/S84_1_fpga_error_moni
  board/piksiv3/rootfs-overlay/etc/init.d/S84_2_reset2defaults
  board/piksiv3/rootfs-overlay/etc/init.d/S84_3_upgrade_tool
  board/piksiv3/rootfs-overlay/etc/init.d/S87pfw_welcome
  package/fpga_error_moni/Config.in
  package/fpga_error_moni/fpga_error_moni.mk
  package/pfw_welcome/Config.in
  package/pfw_welcome/pfw_welcome.mk
  package/pfw_welcome/src/Makefile
  package/pfw_welcome/src/pfw_welcome.c
Labels: Ready to merge
