Repository swift-nav/piksi_buildroot, pull requests merged in 2019-01, with the labels that each got.

#1103 Merge cherry-picks from refs/heads/v2.2.0-release (81865eb9e) into master: Allow standalone logging to create files in F2FS mode [ESD-1005] (#1102)
  package/common_init/overlay/etc/init.d/common.sh
  package/common_init/overlay/etc/init.d/copy_sys_logs.sh
  package/common_init/overlay/etc/init.d/migrate_sdcard.sh
  package/common_init/overlay/etc/init.d/sdcard.sh
  package/common_init/overlay/lib/mdev/automount.sh
  package/common_init/overlay/usr/bin/service_stopped
  package/common_init/overlay/usr/bin/start_service
  package/standalone_file_logger/standalone_file_logger/src/rotating_logger.cc
Labels: auto-merge

#1118 Merge cherry-picks from refs/heads/v2.2.0-release (52ad0aec5) into master: Use PoseDaemon.enc to verify that PoseDaemon exists on device (#1114)
  package/common_init/overlay/etc/init.d/common.sh
Labels: auto-merge

#1122 Merge cherry-picks from refs/heads/v2.2.0-release (22437c40a) into master: aws s3 cp; try --no-sign-request if initial cp fails (#1121)
  scripts/aws-setup.mk
Labels: auto-merge

#1100 Merge cherry-picks from refs/heads/v2.2.0-release (390b49e29) into master: Port reconnect logic from sbp_rx to standalone sub poller (#1097) [ESD-981] [ESD-998]
  package/standalone_file_logger/standalone_file_logger/src/standalone_file_logger.cc
Labels: auto-merge, auto-merge-failed

#1120 EX-499, EX-501: fix GLO TOW rounding in RTCM-SBP converter
  package/gnss_convertors/gnss_convertors.mk
Labels: Ready to merge

#1109 Merge cherry-picks from refs/heads/v2.2.0-release (d74fd3f0c) into master: Fix standalone logging crash [ESD-981] (#1096)
  package/standalone_file_logger/standalone_file_logger/src/Makefile
  package/standalone_file_logger/standalone_file_logger/src/rotating_logger.cc
  package/standalone_file_logger/standalone_file_logger/src/rotating_logger.h
  package/standalone_file_logger/standalone_file_logger/src/standalone_file_logger.cc
  package/standalone_file_logger/standalone_file_logger/test/run_rotating_logger_test.cc
Labels: auto-merge, auto-merge-failed

#1138 Merge cherry-picks from refs/heads/v2.2.0-release (1a16980e5) into master: Use encrypted PoseDaemon filepath to determine whether it exists (#1136)
  package/libpiksi/libpiksi/src/util.c
Labels: auto-merge
